### ISSUE TITLE
Help command - Error

### ISSUE THREAD

**Issue by guillaumearnx** [Ayfri/Basic-CommandHandler#28]
Hello, there is an error with the "help" command when no args are provided

`TypeError: Cannot read property 'includes' of undefined`

**Comment by Ayfri** [comment]
This should be fixed, try the new version, don't forget to delete your `node_modules` folder and to reinstall modules.

**Comment by Ayfri** [comment]
I tested it, and it's really fixed this time.

But I'd advise you to use the v12 version, see on [README](https://github.com/Ayfri/Basic-CommandHandler#how-to-use-it).

**Comment by guillaumearnx** [comment]
V12 minimum or not ? 😅 I'm using v16

**Comment by Ayfri** [comment]
No I mean Discord.js v12.

**Comment by guillaumearnx** [comment]
> No I mean Discord.js v12.

Oh sorry. Download without -b option is for versions under V12 ?

**Comment by Ayfri** [comment]
Yes, it will use Discord.js v11, but as discord.js v11 is not stable anymore (it literally doesn't launch when the bot has a Stage channel in its channels) I'd recommend you to use discord.js v12.
